Traceback (most recent call last):
  File "/Users/Stevington/anaconda/envs/ThesisOSMNX3-6/lib/python3.6/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/Stevington/anaconda/envs/ThesisOSMNX3-6/lib/python3.6/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/Stevington/anaconda/envs/ThesisOSMNX3-6/lib/python3.6/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/Stevington/anaconda/envs/ThesisOSMNX3-6/lib/python3.6/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/Stevington/anaconda/envs/ThesisOSMNX3-6/lib/python3.6/asyncio/base_events.py", line 473, in run_until_complete
    return future.result()
  File "/Users/Stevington/anaconda/envs/ThesisOSMNX3-6/lib/python3.6/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/Stevington/anaconda/envs/ThesisOSMNX3-6/lib/python3.6/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/Stevington/anaconda/envs/ThesisOSMNX3-6/lib/python3.6/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import geowombat as gw
from geowombat.data import rgbn

from rasterio.windows import Window
w = Window(row_off=0, col_off=0, height=100, width=100)

with gw.open(rgbn,
                band_names=['blue', 'green', 'red'],
                num_workers=8,
                indexes=[1, 2, 3],
                window=w,
                out_dtype='float32') as src:
    print(src)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-f99cfce8bf74>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mimport[0m [0mgeowombat[0m [0;32mas[0m [0mgw[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mfrom[0m [0mgeowombat[0m[0;34m.[0m[0mdata[0m [0;32mimport[0m [0mrgbn[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0;32mfrom[0m [0mrasterio[0m[0;34m.[0m[0mwindows[0m [0;32mimport[0m [0mWindow[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mw[0m [0;34m=[0m [0mWindow[0m[0;34m([0m[0mrow_off[0m[0;34m=[0m[0;36m0[0m[0;34m,[0m [0mcol_off[0m[0;34m=[0m[0;36m0[0m[0;34m,[0m [0mheight[0m[0;34m=[0m[0;36m100[0m[0;34m,[0m [0mwidth[0m[0;34m=[0m[0;36m100[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'geowombat'
ModuleNotFoundError: No module named 'geowombat'

