Traceback (most recent call last):
  File "/home/mmann1123/miniconda3/envs/pygis2/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/mmann1123/miniconda3/envs/pygis2/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/mmann1123/miniconda3/envs/pygis2/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/mmann1123/miniconda3/envs/pygis2/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/mmann1123/miniconda3/envs/pygis2/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/mmann1123/miniconda3/envs/pygis2/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/mmann1123/miniconda3/envs/pygis2/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/mmann1123/miniconda3/envs/pygis2/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# List key-value pairs for tags
tags = {'building': True}   

buildings = ox.features_from_place(place_name, tags)
buildings.head()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[6], line 4[0m
[1;32m      1[0m [38;5;66;03m# List key-value pairs for tags[39;00m
[1;32m      2[0m tags [38;5;241m=[39m {[38;5;124m'[39m[38;5;124mbuilding[39m[38;5;124m'[39m: [38;5;28;01mTrue[39;00m}   
[0;32m----> 4[0m buildings [38;5;241m=[39m [43mox[49m[38;5;241;43m.[39;49m[43mfeatures_from_place[49m(place_name, tags)
[1;32m      5[0m buildings[38;5;241m.[39mhead()

[0;31mAttributeError[0m: module 'osmnx' has no attribute 'features_from_place'
AttributeError: module 'osmnx' has no attribute 'features_from_place'

